version: 0.2

phases:
  build:
    commands:
      - sudo apt-get update && sudo apt-get install gulp && apt-get clean && gulp serve

artifacts:
  files:
     - '**/*'
    base-directory: 'output'
   discard-paths: yes
